refresh_rate: 999999 # minutes

br:
    api:
        external: http://datasource.coronacidades.org/
        local: http://45.55.43.231:7000/
        endpoints:
            escolasegura:
                city: "br/cities/safeschools/main"
                students: "br/cities/safeschools/students"
simule:
    class:
        max_students_per_class: 15
        hours_per_week: 40
        hours_per_lecture: 2
        lectures_per_student:
            equitative: 1
            priority: 5
    supplies:
        mask_time_limit: 3
        sanitizer_per_person_per_hour: 0.002
        people_per_thermometer: 100

