refresh_rate: 999999 # minutes

br:
    api:
        external: http://datasource.coronacidades.org/
        local: http://45.55.43.231:7000/
        endpoints:
            escolasegura:
                city: "br/cities/safeschools/main"
                students: "br/cities/safeschools/students"
    simule:
        supplies:
            mask_time_limit: 3
            sanitizer_per_person_per_hour: 0.002
            people_per_thermometer: 100
    farolcovid:
        config: https://raw.githubusercontent.com/ImpulsoGov/farolcovid/stable/src/configs/config.yaml
        elements:
            altíssimo:
                href: "https://i.imgur.com/LJVEtmB.png"
                url: href + ".png"
                color: "red-text"
                description: "Há um crescente número de casos de Covid-19 e grande parte deles não são detectados."
            alto:
                href: "https://i.imgur.com/onZbg2W.png"
                url: href + ".png"
                color: "orange-text"
                description: "Há muitos casos de Covid-19 com transmissão comunitária. A presença de casos não detectados é provável."
            moderado:
                href: "https://i.imgur.com/QYYCMXz.png"
                url: href + ".png"
                color: "yellow-text"
                description: "Há um número moderado de casos e a maioria tem uma fonte de transmissão conhecida."
            "novo normal":
                href: "https://i.imgur.com/Y9tnAg4.png"
                url: href + ".png"
                color: "blue-text"
                description: "Casos são raros e técnicas de rastreamento de contato e monitoramento de casos suspeitos evitam disseminação."
    imgs_source:
        monitor_notify_icon: "https://www.flaticon.com/free-icon/promote_3437346"
        monitor_plan_icon: "https://www.flaticon.com/free-icon/whiteboard_1205484"
        plan_protocol_icon: "https://www.flaticon.com/free-icon/seo_1055689"
        plan_ruler_icon: "https://www.flaticon.com/free-icon/drawing_335233"
        plan_steps_icon: "https://www.flaticon.com/free-icon/timeline_1205528"
        prepare_verify_icon: "https://www.flaticon.com/free-icon/test_1039328"
        simulation_main_icon: "https://www.flaticon.com/free-icon/blackboard_501431"
        simulation_mask_icon: "https://www.flaticon.com/free-icon/medical-mask_1535223"
        simulation_sanitizer_icon: "https://www.flaticon.com/free-icon/hand-sanitizer_2840254"
        simulation_student_icon: "https://www.flaticon.com/free-icon/asking_538924"
        simulation_teacher_icon: "https://www.flaticon.com/free-icon/class_538899"
        simulation_thermometer_icon: "https://www.flaticon.com/free-icon/thermometer_615576"
        