refresh_rate: 999999 # minutes

br:
    api:
        external: http://datasource.coronacidades.org/
        local: http://45.55.43.231:7000/
        endpoints:
            escolasegura:
                city: "br/cities/safeschools/main"
                students: "br/cities/safeschools/students"
    simule:
        class:
            hours_per_week: 40
            hours_per_lecture: 2
            lectures_per_student:
                equitative: 1
                priority: 5
        supplies:
            mask_time_limit: 3
            sanitizer_per_person_per_hour: 0.002
            people_per_thermometer: 100
    farolcovid:
        config: https://raw.githubusercontent.com/ImpulsoGov/farolcovid/stable/src/configs/config.yaml
        elements:
            altíssimo:
                href: "https://i.imgur.com/LJVEtmB.png"
                url: href + ".png"
                color: "red-text"
                description: "Há um crescente número de casos de Covid-19 e grande parte deles não são detectados."
            alto:
                href: "https://i.imgur.com/onZbg2W.png"
                url: href + ".png"
                color: "orange-text"
                description: "Há muitos casos de Covid-19 com transmissão comunitária. A presença de casos não detectados é provável."
            moderado:
                href: "https://i.imgur.com/QYYCMXz.png"
                url: href + ".png"
                color: "yellow-text"
                description: "Há um número moderado de casos e a maioria tem uma fonte de transmissão conhecida."
            "novo normal":
                href: "https://i.imgur.com/Y9tnAg4.png"
                url: href + ".png"
                color: "blue-text"
                description: "Casos são raros e técnicas de rastreamento de contato e monitoramento de casos suspeitos evitam disseminação."
        